dist: bionic
language: python

python:
  - '3.8'

addons:
 
  firefox: latest

before_script:
 
  - install-webdrivers
  - psql -c 'create database test_postgres_db;' -U postgres

install:
  - pip install pipenv
  - pipenv install --dev


branch:
   only:
    - dev
  

services:
  - postgresql

script:
  - python manage.py test read_books