# Generated by Django 3.1.4 on 2020-12-31 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_id', models.CharField(max_length=30)),
                ('slug', models.SlugField(unique=True)),
                ('book_name', models.CharField(max_length=150)),
                ('author', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=10000)),
                ('picture', models.CharField(max_length=350)),
                ('picture_detail', models.CharField(max_length=350)),
            ],
            options={
                'verbose_name': 'book',
                'ordering': ['book_name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=150, null=True, unique=True)),
            ],
            options={
                'ordering': ['category_name'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_favorites', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_favorites', to='read_books.book')),
            ],
        ),
    ]
