# Generated by Django 3.1.4 on 2020-12-07 12:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
