# Generated by Django 3.1.4 on 2020-12-07 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_books', '0002_book_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='comment',
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.CharField(default=1, max_length=550),
            preserve_default=False,
        ),
    ]
