# Generated by Django 3.1.4 on 2020-12-04 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('read_books', '0002_auto_20201204_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='notation',
        ),
    ]
