# Generated by Django 3.1.2 on 2020-12-01 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('read_books', '0002_auto_20201201_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='category',
        ),
    ]
