# Generated by Django 3.1.4 on 2020-12-27 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('read_books', '0003_auto_20201227_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='score',
        ),
    ]
