# Generated by Django 3.1.4 on 2020-12-04 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('read_books', '0003_remove_book_notation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['book_name'], 'verbose_name': 'book'},
        ),
    ]
