# Generated by Django 3.1.2 on 2020-12-01 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_books', '0003_remove_book_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='comment',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='picture',
            field=models.CharField(default=1, max_length=350),
            preserve_default=False,
        ),
    ]
