# Generated by Django 3.1.4 on 2020-12-07 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_books', '0004_auto_20201207_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.CharField(max_length=2000),
        ),
    ]
