# Generated by Django 3.1.4 on 2020-12-07 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_books', '0005_auto_20201207_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.CharField(max_length=10000),
        ),
    ]
