# Generated by Django 3.1.4 on 2020-12-24 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_books', '0005_book_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
