# Generated by Django 3.1.4 on 2020-12-09 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_books', '0006_auto_20201207_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='picture_detail',
            field=models.CharField(default=1, max_length=350),
            preserve_default=False,
        ),
    ]
